# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ZK-Book Exercises Solutions
author: sripwoud
logo: https://static.wixstatic.com/media/c0c19a_059ab29b829d4551bbd7426996089b9e~mv2.png/v1/crop/x_501,y_634,w_2160,h_2693/fill/w_676,h_844,al_c,q_95,enc_auto/Rareskills%20ZK%20Book%20Transparent.png

execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sripwoud/zk-book # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: _media/icon.png
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - amsmath

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_theme_options:
      navigation_with_keys: true
