name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            build = { run = "jupyter-book build --path-output . docs" }
            [tools]
            "pipx:jupyter-book" = "latest"
            uv = "latest"
      - name: Build book
        run: mise run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deploy
