name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - justfile

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build the book
      run: jupyter-book build --path-output . docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html