name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v23

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        cache: poetry
        python-version: 3.10

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.cache  # the path depends on the OS
        key: poetry-0  # increment to reset cache

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Build the book
      run: jupyter-book build --path-output . docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html