name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_py_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            **/*.ipynb
            **/*.py
            .python-version
            pyproject.toml
            uv.lock

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check-format" = { run = "dprint check --excludes mise.toml" }
            "check-lint" = { run = "ruff check" }
            "check" = { depends = "check-*" }
            [tools]
            dprint = "latest"
            ruff = "latest"
      - run: mise r check
